/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package qltienluong;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import static qltienluong.funcTion.checkYear;

/**
 *
 * @author Administrator
 */
public class frmMain extends javax.swing.JFrame {
    
    private ArrayList<ttNhanVien> list, list2;
    DefaultTableModel model, model2;
    
    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
        setLocationRelativeTo(null);
        list = new DAO().getDSNhanVien();
        list2 = new DAOLuong().getDSLuong();
        model = (DefaultTableModel) tblNhanVien.getModel();
        model2 = (DefaultTableModel) tblLuong.getModel();
        
        model.setColumnIdentifiers(new Object[]{
            "Mã NV", "Họ & Tên", "SĐT", "Giới Tính", "Ngày Sinh", "Chức Vụ", "Địa Chỉ"
        });
        model2.setColumnIdentifiers(new Object[]{
            "Mã NV", "Họ & Tên", "Tháng", "Lương"
        });
        
        
        showTable();
    }
    
    public void showTable() {
        for (ttNhanVien nv : list) {
            model.addRow(new Object[]{
                nv.getMaNV(), nv.getHoTen(), nv.getSDT(), nv.getGioiTinh(), nv.getNgaySinh(), nv.getChucVu(), nv.getDiaChi()
            });
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupGioiTinh = new javax.swing.ButtonGroup();
        pnMain = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        QLNV = new javax.swing.JPanel();
        pnHeader = new javax.swing.JPanel();
        lblQLNV = new javax.swing.JLabel();
        lblMaNV = new javax.swing.JLabel();
        lblHoTen = new javax.swing.JLabel();
        lblSDT = new javax.swing.JLabel();
        lblGioiTinh = new javax.swing.JLabel();
        lblNgaySinh = new javax.swing.JLabel();
        lblChucVu = new javax.swing.JLabel();
        lblDiaChi = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        txtHoTen = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        cbxNgay = new javax.swing.JComboBox<>();
        cbxNam = new javax.swing.JComboBox<>();
        cbxThang = new javax.swing.JComboBox<>();
        txtDiaChi = new javax.swing.JTextField();
        pnTacVu = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        scrpnTable = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();
        radNam = new javax.swing.JRadioButton();
        radNu = new javax.swing.JRadioButton();
        cbxChucVu = new javax.swing.JComboBox<>();
        QLL = new javax.swing.JPanel();
        pnHeader2 = new javax.swing.JPanel();
        lblQLCC = new javax.swing.JLabel();
        lblMaNV2 = new javax.swing.JLabel();
        lblHoTen2 = new javax.swing.JLabel();
        lblSDT2 = new javax.swing.JLabel();
        lblChucVu2 = new javax.swing.JLabel();
        txtMaNV2 = new javax.swing.JTextField();
        txtHoTen2 = new javax.swing.JTextField();
        txtSDT2 = new javax.swing.JTextField();
        txtGioLam = new javax.swing.JTextField();
        btnTimNV = new javax.swing.JButton();
        lblDonVi = new javax.swing.JLabel();
        pnMiddle = new javax.swing.JPanel();
        lblTinhLuong = new javax.swing.JLabel();
        lblMaNVTinh = new javax.swing.JLabel();
        txtMaNVTinh = new javax.swing.JTextField();
        btnTinhLuong = new javax.swing.JButton();
        lblTongLuong = new javax.swing.JLabel();
        txtTongLuong = new javax.swing.JTextField();
        lblDonViLuong = new javax.swing.JLabel();
        scrpnLuong = new javax.swing.JScrollPane();
        tblLuong = new javax.swing.JTable();
        pnTacVu1 = new javax.swing.JPanel();
        btnLuu = new javax.swing.JButton();
        btnCapNhat1 = new javax.swing.JButton();
        btnXoa1 = new javax.swing.JButton();
        btnReset1 = new javax.swing.JButton();
        lblNgayLam = new javax.swing.JLabel();
        txtChucVu2 = new javax.swing.JTextField();
        lblGioLam1 = new javax.swing.JLabel();
        txtNgayLam = new javax.swing.JTextField();
        lblThangCT = new javax.swing.JLabel();
        cbxThang2 = new javax.swing.JComboBox<>();
        cbxNam2 = new javax.swing.JComboBox<>();
        btnThemBL = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnMain.setBackground(new java.awt.Color(255, 255, 255));

        QLNV.setBackground(new java.awt.Color(255, 255, 255));

        pnHeader.setBackground(new java.awt.Color(4, 170, 109));

        lblQLNV.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        lblQLNV.setForeground(new java.awt.Color(255, 255, 255));
        lblQLNV.setText("Quản Lý Nhân Viên");

        javax.swing.GroupLayout pnHeaderLayout = new javax.swing.GroupLayout(pnHeader);
        pnHeader.setLayout(pnHeaderLayout);
        pnHeaderLayout.setHorizontalGroup(
            pnHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnHeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblQLNV)
                .addGap(364, 364, 364))
        );
        pnHeaderLayout.setVerticalGroup(
            pnHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnHeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblQLNV)
                .addContainerGap())
        );

        lblMaNV.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblMaNV.setForeground(new java.awt.Color(4, 170, 109));
        lblMaNV.setText("Mã Nhân Viên:");

        lblHoTen.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblHoTen.setForeground(new java.awt.Color(4, 170, 109));
        lblHoTen.setText("Họ & Tên:");

        lblSDT.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblSDT.setForeground(new java.awt.Color(4, 170, 109));
        lblSDT.setText("Số Điện Thoại:");

        lblGioiTinh.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblGioiTinh.setForeground(new java.awt.Color(4, 170, 109));
        lblGioiTinh.setText("Giới Tính:");

        lblNgaySinh.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblNgaySinh.setForeground(new java.awt.Color(4, 170, 109));
        lblNgaySinh.setText("Ngày Sinh:");

        lblChucVu.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblChucVu.setForeground(new java.awt.Color(4, 170, 109));
        lblChucVu.setText("Chức Vụ:");

        lblDiaChi.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblDiaChi.setForeground(new java.awt.Color(4, 170, 109));
        lblDiaChi.setText("Địa Chỉ:");

        cbxNgay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        cbxNam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005" }));

        cbxThang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        txtDiaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaChiActionPerformed(evt);
            }
        });

        pnTacVu.setBackground(new java.awt.Color(4, 170, 109));
        pnTacVu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnThem.setBackground(new java.awt.Color(255, 255, 255));
        btnThem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnThem.setForeground(new java.awt.Color(4, 170, 109));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/AddMem.png"))); // NOI18N
        btnThem.setText("Thêm Mới");
        btnThem.setHideActionText(true);
        btnThem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThem.setIconTextGap(1);
        btnThem.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnThem.setMaximumSize(new java.awt.Dimension(581, 521));
        btnThem.setMinimumSize(new java.awt.Dimension(581, 521));
        btnThem.setPreferredSize(new java.awt.Dimension(581, 521));
        btnThem.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnThem.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnCapNhat.setBackground(new java.awt.Color(255, 255, 255));
        btnCapNhat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCapNhat.setForeground(new java.awt.Color(4, 170, 109));
        btnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Update.png"))); // NOI18N
        btnCapNhat.setText("Cập Nhật");
        btnCapNhat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCapNhat.setIconTextGap(1);
        btnCapNhat.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnCapNhat.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnCapNhat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(255, 255, 255));
        btnXoa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(4, 170, 109));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/DeleteMem.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnXoa.setIconTextGap(1);
        btnXoa.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnXoa.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnXoa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(255, 255, 255));
        btnReset.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnReset.setForeground(new java.awt.Color(4, 170, 109));
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Reset.png"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReset.setIconTextGap(1);
        btnReset.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnReset.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnReset.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnTacVuLayout = new javax.swing.GroupLayout(pnTacVu);
        pnTacVu.setLayout(pnTacVuLayout);
        pnTacVuLayout.setHorizontalGroup(
            pnTacVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTacVuLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(pnTacVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(pnTacVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCapNhat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );
        pnTacVuLayout.setVerticalGroup(
            pnTacVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTacVuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnTacVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCapNhat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(pnTacVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        tblNhanVien.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã NV", "Họ & Tên", "SĐT", "Giới Tính", "Ngày Sinh", "Chức Vụ", "Địa Chỉ"
            }
        ));
        tblNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhanVienMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblNhanVien);

        scrpnTable.setViewportView(jScrollPane2);

        btnGroupGioiTinh.add(radNam);
        radNam.setSelected(true);
        radNam.setText("Nam");
        radNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radNamActionPerformed(evt);
            }
        });

        btnGroupGioiTinh.add(radNu);
        radNu.setText("Nữ");

        cbxChucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nhân Viên", "Trưởng Nhóm" }));

        javax.swing.GroupLayout QLNVLayout = new javax.swing.GroupLayout(QLNV);
        QLNV.setLayout(QLNVLayout);
        QLNVLayout.setHorizontalGroup(
            QLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(QLNVLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(QLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblSDT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblMaNV, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblHoTen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblGioiTinh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblNgaySinh)
                    .addComponent(lblChucVu)
                    .addComponent(lblDiaChi))
                .addGap(33, 33, 33)
                .addGroup(QLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(QLNVLayout.createSequentialGroup()
                        .addGroup(QLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtHoTen)
                            .addComponent(txtMaNV)
                            .addComponent(txtSDT)
                            .addGroup(QLNVLayout.createSequentialGroup()
                                .addComponent(cbxNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbxThang, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbxNam, 0, 74, Short.MAX_VALUE))
                            .addGroup(QLNVLayout.createSequentialGroup()
                                .addComponent(radNam)
                                .addGap(18, 18, 18)
                                .addComponent(radNu))
                            .addComponent(cbxChucVu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnTacVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
            .addComponent(scrpnTable, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        QLNVLayout.setVerticalGroup(
            QLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QLNVLayout.createSequentialGroup()
                .addComponent(pnHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(QLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QLNVLayout.createSequentialGroup()
                        .addGroup(QLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaNV)
                            .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(QLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHoTen)
                            .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(QLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSDT)
                            .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(QLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGioiTinh)
                            .addComponent(radNam)
                            .addComponent(radNu))
                        .addGap(18, 18, 18)
                        .addGroup(QLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNgaySinh)
                            .addComponent(cbxNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxNam, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxThang, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(QLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(QLNVLayout.createSequentialGroup()
                                .addComponent(lblChucVu)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(cbxChucVu)))
                    .addComponent(pnTacVu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(QLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiaChi)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(scrpnTable, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Quản Lý Nhân Viên", QLNV);

        QLL.setBackground(new java.awt.Color(255, 255, 255));

        pnHeader2.setBackground(new java.awt.Color(4, 170, 109));

        lblQLCC.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        lblQLCC.setForeground(new java.awt.Color(255, 255, 255));
        lblQLCC.setText("Quản Lý Chấm Công");

        javax.swing.GroupLayout pnHeader2Layout = new javax.swing.GroupLayout(pnHeader2);
        pnHeader2.setLayout(pnHeader2Layout);
        pnHeader2Layout.setHorizontalGroup(
            pnHeader2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHeader2Layout.createSequentialGroup()
                .addGap(357, 357, 357)
                .addComponent(lblQLCC)
                .addContainerGap(409, Short.MAX_VALUE))
        );
        pnHeader2Layout.setVerticalGroup(
            pnHeader2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnHeader2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblQLCC)
                .addContainerGap())
        );

        lblMaNV2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblMaNV2.setForeground(new java.awt.Color(4, 170, 109));
        lblMaNV2.setText("Mã Nhân Viên:");

        lblHoTen2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblHoTen2.setForeground(new java.awt.Color(4, 170, 109));
        lblHoTen2.setText("Họ & Tên:");

        lblSDT2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblSDT2.setForeground(new java.awt.Color(4, 170, 109));
        lblSDT2.setText("Số Điện Thoại:");

        lblChucVu2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblChucVu2.setForeground(new java.awt.Color(4, 170, 109));
        lblChucVu2.setText("Chức Vụ:");

        txtMaNV2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaNV2ActionPerformed(evt);
            }
        });

        btnTimNV.setBackground(new java.awt.Color(4, 170, 109));
        btnTimNV.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTimNV.setForeground(new java.awt.Color(255, 255, 255));
        btnTimNV.setText("Tìm Nhân Viên");
        btnTimNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimNVActionPerformed(evt);
            }
        });

        lblDonVi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDonVi.setForeground(new java.awt.Color(51, 51, 51));
        lblDonVi.setText("(Giờ)");

        pnMiddle.setBackground(new java.awt.Color(4, 170, 109));

        lblTinhLuong.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        lblTinhLuong.setForeground(new java.awt.Color(255, 255, 255));
        lblTinhLuong.setText("Tính Lương");

        javax.swing.GroupLayout pnMiddleLayout = new javax.swing.GroupLayout(pnMiddle);
        pnMiddle.setLayout(pnMiddleLayout);
        pnMiddleLayout.setHorizontalGroup(
            pnMiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMiddleLayout.createSequentialGroup()
                .addGap(409, 409, 409)
                .addComponent(lblTinhLuong)
                .addContainerGap(440, Short.MAX_VALUE))
        );
        pnMiddleLayout.setVerticalGroup(
            pnMiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnMiddleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTinhLuong)
                .addContainerGap())
        );

        lblMaNVTinh.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblMaNVTinh.setForeground(new java.awt.Color(4, 170, 109));
        lblMaNVTinh.setText("Nhập Mã Nhân Viên Muốn Tính Lương:");

        btnTinhLuong.setBackground(new java.awt.Color(4, 170, 109));
        btnTinhLuong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTinhLuong.setForeground(new java.awt.Color(255, 255, 255));
        btnTinhLuong.setText("Tính Lương");
        btnTinhLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhLuongActionPerformed(evt);
            }
        });

        lblTongLuong.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblTongLuong.setForeground(new java.awt.Color(4, 170, 109));
        lblTongLuong.setText("Tổng Lương:");

        lblDonViLuong.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDonViLuong.setText("Đồng");

        tblLuong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã NV", "Tên Nhân Viên", "Tháng", "Lương"
            }
        ));
        scrpnLuong.setViewportView(tblLuong);

        pnTacVu1.setBackground(new java.awt.Color(4, 170, 109));
        pnTacVu1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnLuu.setBackground(new java.awt.Color(255, 255, 255));
        btnLuu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLuu.setForeground(new java.awt.Color(4, 170, 109));
        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Save.png"))); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.setHideActionText(true);
        btnLuu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLuu.setIconTextGap(1);
        btnLuu.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnLuu.setMaximumSize(new java.awt.Dimension(581, 521));
        btnLuu.setMinimumSize(new java.awt.Dimension(581, 521));
        btnLuu.setPreferredSize(new java.awt.Dimension(581, 521));
        btnLuu.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnLuu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnCapNhat1.setBackground(new java.awt.Color(255, 255, 255));
        btnCapNhat1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCapNhat1.setForeground(new java.awt.Color(4, 170, 109));
        btnCapNhat1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Update.png"))); // NOI18N
        btnCapNhat1.setText("Cập Nhật");
        btnCapNhat1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCapNhat1.setIconTextGap(1);
        btnCapNhat1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnCapNhat1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnCapNhat1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCapNhat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhat1ActionPerformed(evt);
            }
        });

        btnXoa1.setBackground(new java.awt.Color(255, 255, 255));
        btnXoa1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnXoa1.setForeground(new java.awt.Color(4, 170, 109));
        btnXoa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/DeleteMem.png"))); // NOI18N
        btnXoa1.setText("Xóa");
        btnXoa1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnXoa1.setIconTextGap(1);
        btnXoa1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnXoa1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnXoa1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnXoa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa1ActionPerformed(evt);
            }
        });

        btnReset1.setBackground(new java.awt.Color(255, 255, 255));
        btnReset1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnReset1.setForeground(new java.awt.Color(4, 170, 109));
        btnReset1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Reset.png"))); // NOI18N
        btnReset1.setText("Reset");
        btnReset1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReset1.setIconTextGap(1);
        btnReset1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnReset1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnReset1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReset1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnTacVu1Layout = new javax.swing.GroupLayout(pnTacVu1);
        pnTacVu1.setLayout(pnTacVu1Layout);
        pnTacVu1Layout.setHorizontalGroup(
            pnTacVu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTacVu1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(pnTacVu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(pnTacVu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCapNhat1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );
        pnTacVu1Layout.setVerticalGroup(
            pnTacVu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTacVu1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(pnTacVu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCapNhat1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(pnTacVu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnXoa1, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(btnReset1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        lblNgayLam.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblNgayLam.setForeground(new java.awt.Color(4, 170, 109));
        lblNgayLam.setText("Ngày Làm:");

        lblGioLam1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblGioLam1.setForeground(new java.awt.Color(4, 170, 109));
        lblGioLam1.setText("Giờ Làm:");

        lblThangCT.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblThangCT.setForeground(new java.awt.Color(4, 170, 109));
        lblThangCT.setText("Tháng Cần Tính:");

        cbxThang2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        cbxNam2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2021", "2022", "2023", "2024", "2025" }));

        btnThemBL.setBackground(new java.awt.Color(4, 170, 109));
        btnThemBL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnThemBL.setForeground(new java.awt.Color(255, 255, 255));
        btnThemBL.setText("Thêm");
        btnThemBL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemBLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout QLLLayout = new javax.swing.GroupLayout(QLL);
        QLL.setLayout(QLLLayout);
        QLLLayout.setHorizontalGroup(
            QLLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QLLLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(QLLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QLLLayout.createSequentialGroup()
                        .addGroup(QLLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(QLLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(QLLLayout.createSequentialGroup()
                                    .addGroup(QLLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblHoTen2)
                                        .addComponent(lblMaNV2))
                                    .addGap(35, 35, 35)
                                    .addGroup(QLLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(QLLLayout.createSequentialGroup()
                                            .addComponent(txtMaNV2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnTimNV))
                                        .addComponent(txtHoTen2)))
                                .addGroup(QLLLayout.createSequentialGroup()
                                    .addGroup(QLLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(QLLLayout.createSequentialGroup()
                                            .addComponent(lblSDT2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(QLLLayout.createSequentialGroup()
                                            .addComponent(lblChucVu2)
                                            .addGap(74, 74, 74)))
                                    .addGroup(QLLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtSDT2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtChucVu2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(QLLLayout.createSequentialGroup()
                                            .addComponent(txtGioLam, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lblDonVi))
                                        .addComponent(txtNgayLam, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(66, 66, 66)))
                            .addGroup(QLLLayout.createSequentialGroup()
                                .addComponent(lblNgayLam)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 357, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(105, 105, 105))
                    .addGroup(QLLLayout.createSequentialGroup()
                        .addComponent(lblGioLam1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(pnTacVu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
            .addGroup(QLLLayout.createSequentialGroup()
                .addGroup(QLLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnHeader2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(QLLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(QLLLayout.createSequentialGroup()
                            .addGap(52, 52, 52)
                            .addGroup(QLLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblMaNVTinh)
                                .addGroup(QLLLayout.createSequentialGroup()
                                    .addComponent(lblTongLuong)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtTongLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lblThangCT))
                            .addGap(18, 18, 18)
                            .addGroup(QLLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(QLLLayout.createSequentialGroup()
                                    .addComponent(lblDonViLuong)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnThemBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(txtMaNVTinh)
                                .addComponent(btnTinhLuong, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                .addGroup(QLLLayout.createSequentialGroup()
                                    .addComponent(cbxThang2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cbxNam2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGap(34, 34, 34)
                            .addComponent(scrpnLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(60, 60, 60))
                        .addComponent(pnMiddle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        QLLLayout.setVerticalGroup(
            QLLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QLLLayout.createSequentialGroup()
                .addComponent(pnHeader2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(QLLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnTacVu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(QLLLayout.createSequentialGroup()
                        .addGroup(QLLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaNV2)
                            .addComponent(txtMaNV2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTimNV))
                        .addGap(18, 18, 18)
                        .addGroup(QLLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHoTen2)
                            .addComponent(txtHoTen2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(QLLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSDT2)
                            .addComponent(txtSDT2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(QLLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblChucVu2)
                            .addComponent(txtChucVu2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(QLLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNgayLam)
                            .addComponent(txtNgayLam, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(QLLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGioLam1)
                            .addComponent(txtGioLam, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDonVi))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(pnMiddle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(QLLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QLLLayout.createSequentialGroup()
                        .addGroup(QLLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaNVTinh)
                            .addComponent(txtMaNVTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(QLLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblThangCT)
                            .addComponent(cbxThang2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxNam2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnTinhLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(QLLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTongLuong)
                            .addComponent(txtTongLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDonViLuong)
                            .addComponent(btnThemBL, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(scrpnLuong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        jTabbedPane1.addTab("Quản Lý Lương", QLL);

        javax.swing.GroupLayout pnMainLayout = new javax.swing.GroupLayout(pnMain);
        pnMain.setLayout(pnMainLayout);
        pnMainLayout.setHorizontalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMainLayout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnMainLayout.setVerticalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimNVActionPerformed
        String manv = txtMaNV2.getText();
        if (manv.equals("")){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Mã NV muốn tìm!");
            txtMaNV2.requestFocus();
        } else {
            for (ttNhanVien nv : list){
                if (nv.getMaNV().equals(manv)){
//                    JOptionPane.showMessageDialog(this, manv);
                    txtHoTen2.setText(nv.getHoTen());
                    txtSDT2.setText(nv.getSDT());
                    txtChucVu2.setText(nv.getChucVu());
                }
            }
        }
        
    }//GEN-LAST:event_btnTimNVActionPerformed

    private void txtMaNV2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaNV2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaNV2ActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtMaNV.setText("");
        txtHoTen.setText("");
        txtSDT.setText("");
        txtDiaChi.setText("");
        txtMaNV.requestFocus();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
        
        ButtonModel gioitinh = btnGroupGioiTinh.getSelection();
        String gT = "";
        if (radNam.isSelected()) gT = "Nam";
        if (radNu.isSelected()) gT = "Nữ";

        String nams = cbxNam.getSelectedItem().toString();
        int year = Integer.parseInt(nams);
        String thangs = cbxThang.getSelectedItem().toString();
        int month = Integer.parseInt(thangs);
        String ngays = cbxNgay.getSelectedItem().toString();
        int day = Integer.parseInt(ngays);
        
        String dob = ngays+ "/" +thangs+ "/" +nams;
        
        ttNhanVien nv =  new ttNhanVien();
 
        nv.setMaNV(txtMaNV.getText());
        nv.setHoTen(txtHoTen.getText());
        nv.setSDT(txtSDT.getText());
        nv.setGioiTinh(gT);
        nv.setNgaySinh(dob);
        nv.setChucVu(cbxChucVu.getSelectedItem().toString());
        nv.setDiaChi(txtDiaChi.getText());
        
        if(new DAO().capNhatTTNV(nv)){
                JOptionPane.showMessageDialog(rootPane, "Cập nhật thành công!");
//                reload();
                  
            } else{
                JOptionPane.showMessageDialog(rootPane, "Cập nhật không thành công, kiểm tra lại các thông tin đã nhập!");
            }
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        String err = "";
        
        String diachi = txtDiaChi.getText();
        if (diachi.equals("")){
            err = "Vui lòng nhập Địa chỉ!\n\n" +err;
            txtDiaChi.requestFocus();
        }
        

        String sdt = txtSDT.getText();
        if (sdt.equals("")){
            err = "Vui lòng nhập Số điện thoại!\n\n" +err;
            txtSDT.requestFocus();
        }
        else {
            for (int i=0; i<sdt.length(); i++)
            if (sdt.charAt(i) > '9' || sdt.charAt(i) < '0'){
                err = "Vui lòng nhập Số điện thoại là chữ số!\n\n" +err;
                txtSDT.requestFocus();
                break;
            }
        }
        
        String hoten = txtHoTen.getText();
        if (hoten.equals("")){
            err = "Vui lòng nhập Họ tên!\n\n" +err;
            txtHoTen.requestFocus();
        }
        
        String manv = txtMaNV.getText();
        if (manv.length() != 5){
                err = "Vui lòng nhập Mã NV với định dạng 5 chữ số!\n\n" +err;
                txtMaNV.requestFocus();
        }
        else {
            for (int i=0; i<manv.length(); i++)
            if (manv.charAt(i) > '9' || manv.charAt(i) < '0'){
                err = "Vui lòng nhập Mã NV là chữ số!\n\n" +err;
                txtMaNV.requestFocus();
                break; 
            }
        }

        ButtonModel gioitinh = btnGroupGioiTinh.getSelection();
        String gT = "";
        if (radNam.isSelected()) gT = "Nam";
        if (radNu.isSelected()) gT = "Nữ";

        String nams = cbxNam.getSelectedItem().toString();
        int year = Integer.parseInt(nams);
        String thangs = cbxThang.getSelectedItem().toString();
        int month = Integer.parseInt(thangs);
        String ngays = cbxNgay.getSelectedItem().toString();
        int day = Integer.parseInt(ngays);

        if (checkYear(year) == true){
            if (month == 2){
                if (day > 29){
                    err = "Vui lòng nhập ngày sinh đúng!\n\n" +err;
                    cbxNgay.requestFocus();
                }
            } else {
                if (month == 4 || month == 6 || month == 9 || month == 11){
                    if (day > 30){
                        err = "Vui lòng nhập ngày sinh đúng!\n\n" +err;
                        cbxNgay.requestFocus();
                    }
                }
            }
        } else {
            if (month == 2){
                if (day > 28){
                    err = "Vui lòng nhập ngày sinh đúng!\n\n" +err;
                    cbxNgay.requestFocus();
                }
            } else {
                if (month == 4 || month == 6 || month == 9 || month == 11){
                    if (day > 30){
                        err = "Vui lòng nhập ngày sinh đúng!\n\n" +err;
                        cbxNgay.requestFocus();
                    }
                }
            }
        }

        String chucvu = cbxChucVu.getSelectedItem().toString();

        if (err.length() > 0) JOptionPane.showMessageDialog(this, err);
        
        else {
            String dob = ngays+ "/" +thangs+ "/" +nams;

            ttNhanVien nv = new ttNhanVien();
            nv.setMaNV(txtMaNV.getText());
            nv.setHoTen(txtHoTen.getText());
            nv.setSDT(txtSDT.getText());
            nv.setGioiTinh(gT);
            nv.setNgaySinh(dob);
            nv.setChucVu(cbxChucVu.getSelectedItem().toString());
            nv.setDiaChi(txtDiaChi.getText());

            if(new DAO().themNhanVien(nv)){
                JOptionPane.showMessageDialog(rootPane, "Thêm thành công!");
                list.add(nv);
                addShowResult();
            } else{
                JOptionPane.showMessageDialog(rootPane, "Thêm không thành công, kiểm tra lại các thông tin đã nhập!");
            }
        }

    }//GEN-LAST:event_btnThemActionPerformed

    private void txtDiaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaChiActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int ketQua = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắn chắn muốn XÓA nhân viên này ?",
            "Thông báo", JOptionPane.WARNING_MESSAGE, JOptionPane.YES_NO_OPTION);
 
        if(ketQua == JOptionPane.YES_OPTION){
            if(new DAO().xoaNhanVien(txtMaNV.getText())){
                    JOptionPane.showMessageDialog(this, "Xóa thành công!");
                    delShowResult();
                } else{
                    JOptionPane.showMessageDialog(this, "Xóa không thành công!");
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void tblNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhanVienMouseClicked
        // TODO add your handling code here:
        int index = tblNhanVien.getSelectedRow();
        TableModel model = tblNhanVien.getModel();
        
        String manv = model.getValueAt(index, 0).toString();
        String hoten = model.getValueAt(index, 1).toString();
        String sdt = model.getValueAt(index, 2).toString();
        
        String gioitinh = model.getValueAt(index, 3).toString();
        String gt = gioitinh.substring(0, 3);
        
        String ngaysinh = model.getValueAt(index, 4).toString();
        String ngay = ngaysinh.substring(0, 2);
        int day = Integer.parseInt(ngay);
        String thang = ngaysinh.substring(3, 5);
        int month = Integer.parseInt(thang);
        String nam = ngaysinh.substring(6, 10);
        int year = Integer.parseInt(nam);
        
        String chucvu = model.getValueAt(index, 5).toString();
        String cv = chucvu.substring(0, 11);
        
        String diachi = model.getValueAt(index, 6).toString();

        txtMaNV.setText(manv);
        txtHoTen.setText(hoten);
        txtSDT.setText(sdt);
        
        if (gt.equalsIgnoreCase("Nam")) radNam.setSelected(true);
        else radNu.setSelected(true);
        
        cbxNgay.setSelectedIndex(day - 1);
        cbxThang.setSelectedIndex(month - 1);
        cbxNam.setSelectedIndex(year - 1960);
        
        if (cv.equalsIgnoreCase("Trưởng Nhóm")) cbxChucVu.setSelectedIndex(1);
        else cbxChucVu.setSelectedIndex(0);
        
        txtDiaChi.setText(diachi);
    }//GEN-LAST:event_tblNhanVienMouseClicked

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        ttNhanVien nv = new ttNhanVien();
        nv.setMaNV(txtMaNV2.getText());
        nv.setHoTen(txtHoTen2.getText());
        nv.setSDT(txtSDT2.getText());
        nv.setChucVu(txtChucVu2.getText());
        nv.setNgayLam(txtNgayLam.getText());
        nv.setGioLam(txtGioLam.getText());
       
        if(new DAOLuong().themLuong(nv)){
            JOptionPane.showMessageDialog(rootPane, "Thêm thành công!");
            list.add(nv);
            addShowResult();
        } else{
            JOptionPane.showMessageDialog(rootPane, "Thêm không thành công, kiểm tra lại các thông tin đã nhập!");
        }
        
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnCapNhat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhat1ActionPerformed
        // TODO add your handling code here:
        ttNhanVien nv =  new ttNhanVien();
 
        nv.setMaNV(txtMaNV2.getText());
        nv.setNgayLam(txtNgayLam.getText());
        nv.setGioLam(txtGioLam.getText());
        
        if(new DAOLuong().capNhatLuong(nv)){
                JOptionPane.showMessageDialog(rootPane, "Cập nhật thành công!");      
            } else{
                JOptionPane.showMessageDialog(rootPane, "Cập nhật không thành công!");
            }
    }//GEN-LAST:event_btnCapNhat1ActionPerformed

    private void btnXoa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoa1ActionPerformed
        // TODO add your handling code here:
        int ketQua = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắn chắn muốn XÓA ?",
            "Thông báo", JOptionPane.WARNING_MESSAGE, JOptionPane.YES_NO_OPTION);
 
        if(ketQua == JOptionPane.YES_OPTION){
            if(new DAOLuong().xoaLuong(txtMaNV2.getText(), txtNgayLam.getText())){
                    JOptionPane.showMessageDialog(this, "Xóa thành công!");
                    delShowResult();
                } else{
                    JOptionPane.showMessageDialog(this, "Mã NV hoặc Ngày Làm không tồn tại trong dữ liệu!");
            }
        }
    }//GEN-LAST:event_btnXoa1ActionPerformed

    private void btnReset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReset1ActionPerformed
        // TODO add your handling code here:
        txtMaNV2.setText("");
        txtHoTen2.setText("");
        txtSDT2.setText("");
        txtChucVu2.setText("");
        txtNgayLam.setText("");
        txtGioLam.setText("");
        txtMaNV2.requestFocus();
    }//GEN-LAST:event_btnReset1ActionPerformed

    private void radNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radNamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radNamActionPerformed

    private void btnTinhLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhLuongActionPerformed
        // TODO add your handling code here:
        String month = cbxThang2.getSelectedItem().toString();
        String year = cbxNam2.getSelectedItem().toString();
        String mnv = txtMaNVTinh.getText();
        float tongGio = 0.0f;
        float tongLuong = 0.0f;
        float luong1h = 24000;
        String cv = "";
        
        if (mnv.equals("")){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Mã NV cần tính lương!");
            txtMaNVTinh.requestFocus();
        } else {
            for (ttNhanVien nv : list2){
                if (nv.getNgayLam().substring(3, 5).equals(month) && nv.getMaNV().equals(mnv)){
                    float gio = Float.parseFloat(nv.getGioLam());
                    tongGio = tongGio + gio;
                    cv = nv.getChucVu();
                }
            }
            if (cv.substring(0, 9).equals("Nhân Viên")){
                tongLuong = tongGio * luong1h;
                String tL = String.valueOf(tongLuong);
                txtTongLuong.setText(tL);
            } else {
                tongLuong = tongGio * luong1h * 1.25f;
                String tL = String.valueOf(tongLuong);
                txtTongLuong.setText(tL);
            }
            
        }
        
           
    }//GEN-LAST:event_btnTinhLuongActionPerformed

    private void btnThemBLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemBLActionPerformed
        // TODO add your handling code here:
        ttNhanVien nv = new ttNhanVien();
        String mnvNow = txtMaNVTinh.getText();
        String ht = "";
        String thg = "";
        
        for (ttNhanVien nvNow : list2){
            if (nvNow.getMaNV().equals(mnvNow)){
                ht = nvNow.getHoTen();
                thg = nvNow.getNgayLam().substring(3, 10);
            }
        }
        
        nv.setMaNV(mnvNow);
        nv.setHoTen(ht);
        nv.setThangLam(thg);
        nv.setLuong(txtTongLuong.getText());
       
        if(new DAOLuong().themVaoBLuong(nv)){
            JOptionPane.showMessageDialog(rootPane, "Thêm thành công!");
            list2.add(nv);
            addLuongShowResult();
        } else{
            JOptionPane.showMessageDialog(rootPane, "Thêm không thành công!");
        }
    }//GEN-LAST:event_btnThemBLActionPerformed
    
    int i = 1;

    public void addShowResult() {
        ttNhanVien nv = list.get(list.size() - 1);
        model.addRow(new Object[]{
            nv.getMaNV(), nv.getHoTen(), nv.getSDT(), nv.getGioiTinh(), nv.getNgaySinh(), nv.getChucVu(), nv.getDiaChi()
        });
    }
    
    public void addLuongShowResult() {
        ttNhanVien nv = list2.get(list2.size() - 1);
        model2.addRow(new Object[]{
            nv.getMaNV(), nv.getHoTen(), nv.getThangLam(), nv.getLuong()
        });
    }
    
    public void delShowResult() {
        ttNhanVien nv = list.get(list.size() - 1);
        model.removeRow(tblNhanVien.getSelectedRow());
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel QLL;
    private javax.swing.JPanel QLNV;
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnCapNhat1;
    private javax.swing.ButtonGroup btnGroupGioiTinh;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnReset1;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThemBL;
    private javax.swing.JButton btnTimNV;
    private javax.swing.JButton btnTinhLuong;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoa1;
    private javax.swing.JComboBox<String> cbxChucVu;
    private javax.swing.JComboBox<String> cbxNam;
    private javax.swing.JComboBox<String> cbxNam2;
    private javax.swing.JComboBox<String> cbxNgay;
    private javax.swing.JComboBox<String> cbxThang;
    private javax.swing.JComboBox<String> cbxThang2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblChucVu;
    private javax.swing.JLabel lblChucVu2;
    private javax.swing.JLabel lblDiaChi;
    private javax.swing.JLabel lblDonVi;
    private javax.swing.JLabel lblDonViLuong;
    private javax.swing.JLabel lblGioLam1;
    private javax.swing.JLabel lblGioiTinh;
    private javax.swing.JLabel lblHoTen;
    private javax.swing.JLabel lblHoTen2;
    private javax.swing.JLabel lblMaNV;
    private javax.swing.JLabel lblMaNV2;
    private javax.swing.JLabel lblMaNVTinh;
    private javax.swing.JLabel lblNgayLam;
    private javax.swing.JLabel lblNgaySinh;
    private javax.swing.JLabel lblQLCC;
    private javax.swing.JLabel lblQLNV;
    private javax.swing.JLabel lblSDT;
    private javax.swing.JLabel lblSDT2;
    private javax.swing.JLabel lblThangCT;
    private javax.swing.JLabel lblTinhLuong;
    private javax.swing.JLabel lblTongLuong;
    private javax.swing.JPanel pnHeader;
    private javax.swing.JPanel pnHeader2;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPanel pnMiddle;
    private javax.swing.JPanel pnTacVu;
    private javax.swing.JPanel pnTacVu1;
    private javax.swing.JRadioButton radNam;
    private javax.swing.JRadioButton radNu;
    private javax.swing.JScrollPane scrpnLuong;
    private javax.swing.JScrollPane scrpnTable;
    private javax.swing.JTable tblLuong;
    private javax.swing.JTable tblNhanVien;
    private javax.swing.JTextField txtChucVu2;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtGioLam;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtHoTen2;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtMaNV2;
    private javax.swing.JTextField txtMaNVTinh;
    private javax.swing.JTextField txtNgayLam;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtSDT2;
    private javax.swing.JTextField txtTongLuong;
    // End of variables declaration//GEN-END:variables
}
